package server.maps;

public enum MapleMapObjectType {
  NPC, MONSTER, ITEM, PLAYER, DOOR, SUMMON, SHOP, MIST, ATOM, REACTOR, EXTRACTOR, MagicSword, HIRED_MERCHANT, FIELD, WRECK, INCINERATE, ENERGY, SWORD, WEB, POSION, RUNE, ATTACK, RANDOM_PORTAL, SECOND_ATOM, A_SECOND_ATOM, SPECIAL_CHAIR, ORB, SPECIAL_PORTAL, OBSTACLE;
}
