package provider;

public enum MapleDataType {
  NONE, IMG_0x00, SHORT, INT, FLOAT, DOUBLE, STRING, EXTENDED, PROPERTY, CANVAS, VECTOR, CONVEX, SOUND, UOL, UNKNOWN_TYPE, LONG, UNKNOWN_EXTENDED_TYPE;
}
